services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: restadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restdb
    expose:
      - "5432"
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"