services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: restadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restdb
    expose:
      - "5432"